### ISSUE TITLE
app get crash while clicking on back button

### ISSUE THREAD

**Issue by sktniranjan** [Paldom/SpinnerDialog#16]
Here is my log info:
Uncaught exception from plugin
01-12 12:13:01.319: E/PluginManager(4529): android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@2c49beb8 is not valid; is your activity running?
01-12 12:13:01.319: E/PluginManager(4529): 	at android.view.ViewRootImpl.setView(ViewRootImpl.java:513)
01-12 12:13:01.319: E/PluginManager(4529): 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:301)
01-12 12:13:01.319: E/PluginManager(4529): 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:215)
01-12 12:13:01.319: E/PluginManager(4529): 	at android.view.WindowManagerImpl$CompatModeWrapper.addView(WindowManagerImpl.java:140)
01-12 12:13:01.319: E/PluginManager(4529): 	at android.view.Window$LocalWindowManager.addView(Window.java:537)
01-12 12:13:01.319: E/PluginManager(4529): 	at android.app.Dialog.show(Dialog.java:278)
01-12 12:13:01.319: E/PluginManager(4529): 	at hu.dpal.phonegap.plugins.CallbackProgressDialog.show(CallbackProgressDialog.java:29)
01-12 12:13:01.319: E/PluginManager(4529): 	at hu.dpal.phonegap.plugins.SpinnerDialog$1.run(SpinnerDialog.java:50)
01-12 12:13:01.319: E/PluginManager(4529): 	at android.app.Activity.runOnUiThread(Activity.java:4170)
01-12 12:13:01.319: E/PluginManager(4529): 	at hu.dpal.phonegap.plugins.SpinnerDialog.execute(SpinnerDialog.java:63)
01-12 12:13:01.319: E/PluginManager(4529): 	at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:84)
01-12 12:13:01.319: E/PluginManager(4529): 	at org.apache.cordova.PluginManager.exec(PluginManager.java:147)
01-12 12:13:01.319: E/PluginManager(4529): 	at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:59)
01-12 12:13:01.319: E/PluginManager(4529): 	at org.apache.cordova.CordovaBridge.promptOnJsPrompt(CordovaBridge.java:129)
01-12 12:13:01.319: E/PluginManager(4529): 	at org.apache.cordova.CordovaChromeClient.onJsPrompt(CordovaChromeClient.java:192)
01-12 12:13:01.319: E/PluginManager(4529): 	at android.webkit.CallbackProxy.handleMessage(CallbackProxy.java:600)
01-12 12:13:01.319: E/PluginManager(4529): 	at android.os.Handler.dispatchMessage(Handler.java:99)
01-12 12:13:01.319: E/PluginManager(4529): 	at android.os.Looper.loop(Looper.java:137)
01-12 12:13:01.319: E/PluginManager(4529): 	at android.app.ActivityThread.main(ActivityThread.java:4441)
01-12 12:13:01.319: E/PluginManager(4529): 	at java.lang.reflect.Method.invokeNative(Native Method)
01-12 12:13:01.319: E/PluginManager(4529): 	at java.lang.reflect.Method.invoke(Method.java:511)
01-12 12:13:01.319: E/PluginManager(4529): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
01-12 12:13:01.319: E/PluginManager(4529): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
01-12 12:13:01.319: E/PluginManager(4529): 	at dalvik.system.NativeStart.main(Native Method)

**Comment by lukasT** [comment]
got the same here... My first thought would be that maybe a spinner is still present or would get present just after app.exit has been called but that is just a guess.
